// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JlmwXezh7DHYH2oM9FkIeMpX9d-ysrs',
    appId: '1:506023460319:web:43c2ee21bc94b8568d586a',
    messagingSenderId: '506023460319',
    projectId: 'my-zkir-app',
    authDomain: 'my-zkir-app.firebaseapp.com',
    storageBucket: 'my-zkir-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JlmwXezh7DHYH2oM9FkIeMpX9d-ysrs',
    appId: '1:506023460319:android:43c2ee21bc94b8568d586a',
    messagingSenderId: '506023460319',
    projectId: 'my-zkir-app',
    storageBucket: 'my-zkir-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JlmwXezh7DHYH2oM9FkIeMpX9d-ysrs',
    appId: '1:506023460319:ios:43c2ee21bc94b8568d586a',
    messagingSenderId: '506023460319',
    projectId: 'my-zkir-app',
    storageBucket: 'my-zkir-app.appspot.com',
    iosBundleId: 'com.myzikr.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-JlmwXezh7DHYH2oM9FkIeMpX9d-ysrs',
    appId: '1:506023460319:macos:43c2ee21bc94b8568d586a',
    messagingSenderId: '506023460319',
    projectId: 'my-zkir-app',
    storageBucket: 'my-zkir-app.appspot.com',
    iosBundleId: 'com.myzikr.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-JlmwXezh7DHYH2oM9FkIeMpX9d-ysrs',
    appId: '1:506023460319:windows:43c2ee21bc94b8568d586a',
    messagingSenderId: '506023460319',
    projectId: 'my-zkir-app',
    authDomain: 'my-zkir-app.firebaseapp.com',
    storageBucket: 'my-zkir-app.appspot.com',
  );
}
